In [10]:
import explore_r as ex
#standard ds imports
import pandas as pd
import numpy as np
#viz and stats
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
#import modeling as md
import os
import nltk
import unicodedata
import re
#sklearn imports
from sklearn.model_selection import train_test_split
import sklearn.preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix, plot_confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
#CATboost imports
from catboost import CatBoostClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

ModuleNotFoundError: No module named 'explore_r'

In [4]:
df = pd.read_csv('prepped_data.csv')

In [5]:
df

,date,day_of_week,start_time,week_num,home_score,home_wins,away_score,away_wins,temp,humidity,wind,spread,ou,is_under,abnormal_start,total_scores,is_playoff,playoff_implications,is_turf,is_outdoor
0,2023-02-12,Sunday,6,19,35,16,38,16,72,0,0,1.0,51.0,0,0,73,1,1,0,0
1,2023-01-29,Sunday,3,19,31,15,7,15,52,48,14,2.5,45.5,1,0,38,1,1,0,1
2,2023-01-29,Sunday,6,19,23,15,20,14,22,55,13,1.5,48.0,1,0,43,1,1,0,1
3,2023-01-22,Sunday,3,19,10,14,27,13,32,10,0,5.5,49.0,1,0,37,1,1,1,1
4,2023-01-22,Sunday,6,19,19,14,12,13,55,47,19,4.0,47.0,1,0,31,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10806,1979-09-02,Sunday,4,1,14,0,0,0,76,71,8,1.0,37.0,1,0,14,0,0,1,1
10807,1979-09-02,Sunday,4,1,22,0,25,0,73,76,10,2.0,41.0,0,0,47,0,0,0,1
10808,1979-09-02,Sunday,4,1,17,0,24,0,70,77,10,4.0,36.5,0,0,41,0,0,0,1
10809,1979-09-02,Sunday,4,1,16,0,33,0,72,0,0,2.0,42.5,0,0,49,0,0,1,0
10810,1979-09-01,Saturday,8,1,31,0,16,0,79,87,9,3.0,30.0,0,1,47,0,0,0,1

In [7]:
df['spread'] = abs(df['spread'])

In [8]:
train, validate, test = ex.split_data(df)

NameError: name 'ex' is not defined